---
- import_tasks: setup-centos.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Install docker.
  package: name=docker state=present

- name: Ensure docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: pull the docker registry
  command: docker pull registry

- name: Start Docker registry container with certificate information.
  command: docker run -d -p 5000:5000 --restart=always --name registry -v /certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/ca.crt -e REGISTRY_HTTP_TLS_KEY=/certs/ca.key registry
